apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-arm64-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: foobar-arm64.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-arm64-svc
                port:
                  number: 80