sonar.projectKey=gidaltilopes_teste-dot-net-arm64
sonar.working.directory=C:\\Users\\Gidal\\pipeline2\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Gidal\\pipeline2
sonar.pullrequest.cache.basepath=C:\\Users\\Gidal\\pipeline2

BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.projectKey=gidaltilopes_teste-dot-net-arm64:BAC030A7-4652-4554-B563-B7C64CA571FA
BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.projectName=HelloWorld
BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.projectBaseDir=C:\\Users\\Gidal\\pipeline2
BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.sourceEncoding=utf-8
BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.tests=
BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.sources=\
"C:\\Users\\Gidal\\pipeline2\\Program.cs",\
"C:\\Users\\Gidal\\pipeline2\\obj\\Debug\\net8.0\\HelloWorld.GlobalUsings.g.cs",\
"C:\\Users\\Gidal\\pipeline2\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\Gidal\\pipeline2\\obj\\Debug\\net8.0\\HelloWorld.AssemblyInfo.cs",\
"C:\\Users\\Gidal\\pipeline2\\.gitignore",\
"C:\\Users\\Gidal\\pipeline2\\azure-pipelines.yml",\
"C:\\Users\\Gidal\\pipeline2\\Dockerfile",\
"C:\\Users\\Gidal\\pipeline2\\k8s\\deployment.yaml",\
"C:\\Users\\Gidal\\pipeline2\\k8s\\ingress.yaml",\
"C:\\Users\\Gidal\\pipeline2\\k8s\\service.yaml",\
"C:\\Users\\Gidal\\pipeline2\\obj\\HelloWorld.csproj.nuget.dgspec.json",\
"C:\\Users\\Gidal\\pipeline2\\obj\\project.assets.json",\
"C:\\Users\\Gidal\\pipeline2\\bin\\Debug\\net8.0\\HelloWorld.deps.json",\
"C:\\Users\\Gidal\\pipeline2\\bin\\Debug\\net8.0\\HelloWorld.runtimeconfig.json",\
"C:\\Users\\Gidal\\pipeline2\\obj\\Debug\\net8.0\\HelloWorld.sourcelink.json",\
"C:\\Users\\Gidal\\pipeline2\\obj\\Debug\\net8.0\\staticwebassets.build.json"

BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Gidal\\pipeline2\\.sonarqube\\out\\0"
BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Gidal\\pipeline2\\.sonarqube\\out\\0\\Issues.json"
BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.cs.scanner.telemetry=\
"C:\\Users\\Gidal\\pipeline2\\.sonarqube\\out\\0\\Telemetry.json"

BAC030A7-4652-4554-B563-B7C64CA571FA.sonar.working.directory=C:\\Users\\Gidal\\pipeline2\\.sonarqube\\out\\.sonar\\mod0
sonar.organization=gidaltilopes
sonar.visualstudio.enable=false
sonar.host.url=https://sonarcloud.io

sonar.modules=BAC030A7-4652-4554-B563-B7C64CA571FA

